name: ci
on:
  push:
    branches:
      - main

jobs:
  Deploy-DB-Changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install
        run: npm install
      - name: Set DATABASE_URL environment variable
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Run Prisma Migrate and Generate
        run: npx prisma generate && npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Use the secret here
