name: ci
on:
  push:
    branches:
      - main

jobs:
  Deploy-DB-Changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install
        run: npm install
      - name: Deploy DB Changes
        run: DATABASE_URL=${{ secrets.DATABASE_URL }} npx prisma migrate deploy
